config/routes.rb
Icec::Application.routes.draw do
  resources :projects

  resources :tops_qualifiers

  resources :tops_questions

  resources :tops_forms do
    get :tops_form, on: :member
    get :tops_form2, on: :member
    post :tops_form, on: :member
    post :tops_form2, on: :member
  end
  
  resources :email_messages do
    get :preview_email, on: :member
  end

  resources :daily_notes

  resources :child_dailies do
    resources :tops_forms #hmm not working for me
    get :tops_report, on: :member
    post :tops_report, on: :member
  end

  resources :children

  match 'take_attendance' => 'child_dailies#take_attendance'
  match 'roll_call' => 'child_dailies#roll_call'
  match 'indexnames' => 'child_dailies#indexnames'
  match 'generate_emails' => 'email_messages#generate_emails'

  

end

app/controllers/tops_forms_controller.rb
class TopsFormsController < ApplicationController
  # GET /tops_forms
  # GET /tops_forms.json
  def index
    @tops_forms = TopsForm.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tops_forms }
    end
  end

  # GET /tops_forms/1
  # GET /tops_forms/1.json
  def show
    @tops_form = TopsForm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tops_form }
    end
  end

  # GET /tops_forms/new
  # GET /tops_forms/new.json
  def new
    @tops_form = TopsForm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tops_form }
    end
  end

  # GET /tops_forms/1/edit
  def edit
    @tops_form = TopsForm.find(params[:id])
  end

  # POST /tops_forms
  # POST /tops_forms.json
  def create
    @tops_form = TopsForm.new(params[:tops_form])
    @child_daily = ChildDaily.find(params[:tops_form][:question_id])
    current_child_daily.questions(@child_daily)


    respond_to do |format|
      if @tops_form.save
        format.html { redirect_to @tops_form, notice: 'Tops form was successfully created.' }
        format.json { render json: @tops_form, status: :created, location: @tops_form }
      else
        format.html { render action: "new" }
        format.json { render json: @tops_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tops_forms/1
  # PUT /tops_forms/1.json
  def update
    @tops_form = TopsForm.find(params[:id])

    respond_to do |format|
      if @tops_form.update_attributes(params[:tops_form])
        format.html { redirect_to @tops_form, notice: 'Tops form was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tops_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tops_forms/1
  # DELETE /tops_forms/1.json
  def destroy
    @tops_form = TopsForm.find(params[:id])
    @tops_form.destroy

    respond_to do |format|
      format.html { redirect_to tops_forms_url }
      format.json { head :no_content }
    end
  end
  
  def tops_form
    @tops_form = TopsForm.find(params[:id])
    #@questions = TopsQuestion.find(@tops_form.tops_question_id)
    #@child_dailies = ChildDailies.all
    @child_daily = ChildDaily.find(@tops_form.child_daily_id)
    @child = Child.find(@child_daily.child_id)
    @questions = TopsQuestion.all
    @qualifiers = TopsQualifier.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @children }
    end
  end
  
  def tops_form2
    @tops_form = TopsForm.find(params[:id])
    #@questions = TopsQuestion.find(@tops_form.tops_question_id)
    #@child_dailies = ChildDailies.all
    @child_daily = ChildDaily.find(@tops_form.child_daily_id)
    @child = Child.find(@child_daily.child_id)
    @questions = TopsQuestion.all
    @qualifiers = TopsQualifier.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @children }
    end
  end
  
  
  
end

app/helpers/tops_forms_helper.rb
module TopsFormsHelper
end

app/views/tops_forms/_form.html.erb
<%= form_for(@tops_form) do |f| %>
  <% if @tops_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tops_form.errors.count, "error") %> prohibited this tops_form from being saved:</h2>

      <ul>
      <% @tops_form.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :child_daily_id %><br />
    <%= f.number_field :child_daily_id %>
  </div>
  <div class="field">
    <%= f.label :tops_question_id %><br />
    <%= f.number_field :tops_question_id %>
  </div>
  <div class="field">
    <%= f.label :checked %><br />
    <%= f.check_box :checked %>
  </div>
  <div class="field">
    <%= f.label :qualifier_value_id %><br />
    <%= f.number_field :qualifier_value_id %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tops_forms/edit.html.erb
<h1>Editing tops_form</h1>

<%= render 'form' %>

<%= link_to 'Show', @tops_form %> |
<%= link_to 'Back', tops_forms_path %>

app/views/tops_forms/index.html.erb
<h1>Listing tops_forms</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Child daily</th>
    <th>Tops question</th>
    <th>Checked</th>
    <th>Qualifier value</th>
    <th>Note</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tops_forms.each do |tops_form| %>
  <tr>
    <td><%= tops_form.id %></td>
    <td><%= tops_form.child_daily_id %></td>
    <td><%= tops_form.tops_question_id %></td>
    <td><%= tops_form.checked %></td>
    <td><%= tops_form.qualifier_value_id %></td>
    <td><%= tops_form.note %></td>
    <td><%= link_to 'Show', tops_form %></td>
    <td><%= link_to 'Edit', edit_tops_form_path(tops_form) %></td>
    <td><%= link_to 'Destroy', tops_form, confirm: 'Are you sure?', method: :delete %></td>
    <td><%= link_to 'TOPS Form', tops_form2_tops_form_path(tops_form) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tops form', new_tops_form_path %>

app/views/tops_forms/new.html.erb
<h1>New tops_form</h1>

<%= render 'form' %>

<%= link_to 'Back', tops_forms_path %>

app/views/tops_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Child daily:</b>
  <%= @tops_form.child_daily_id %>
</p>

<p>
  <b>Tops question:</b>
  <%= @tops_form.tops_question_id %>
</p>

<p>
  <b>Checked:</b>
  <%= @tops_form.checked %>
</p>

<p>
  <b>Qualifier value:</b>
  <%= @tops_form.qualifier_value_id %>
</p>

<p>
  <b>Note:</b>
  <%= @tops_form.note %>
</p>


<%= link_to 'Edit', edit_tops_form_path(@tops_form) %> |
<%= link_to 'Back', tops_forms_path %>

app/views/tops_forms/tops_form.html.erb
<h1>TOPS Report</h1>
<p>Today is <%= Date.today %><p>
<p><%= "This is an individual TOPS report for " + @child.first_name %><p>

<%# kids = Hash.new() %>

<%= form_tag("tops_form", :method => "post") do %>

  <% @questions.each do |q| %>

    <%# checkbox for this question_id %>
    <%= check_box_tag :question_id, q.id %>
    
    <%# label for this checkbox (question description) %>
    <%= label_tag(:question_id, q.description) %>
    
    <%# radio buttons for qualifier %>
    <%# @qualifiers = TopsQualifier.find(:all q.qualifier_type_id) %>
    <% @qualifiers = TopsQualifier.find(:all, :conditions => { :type_id => q.qualifier_type_id}) %>
    
    <% @qualifiers.each do |qual| %>
      <% if(qual.value_name == '') %>
        <% @label_text = "none" %>
        <% @checked = true %>
      <% else %>
        <% @label_text = qual.value_name %>
        <% @checked = false %>
      <% end %>
      
      <br />
      <%= radio_button_tag q.id, qual.value_id, @checked %>
      <%= label_tag q.id, @label_text %>
    <% end %>
    
    <%# textbox for note %>
    <br />
	<%= label_tag :description, "Note" %><br />
    <%= text_area_tag :description %>

    
    <br />
    <br />
  <% end %>


<br />
  <%= submit_tag("Save Report") %>
<% end %>

app/views/tops_forms/tops_form2.html.erb
<h1>TOPS Report</h1>
<p>Today is <%= Date.today %><p>

<%# debug @questions %>
<%# debug @child %>
<%= form_for(@tops_form) do |f| %>
 
  <%= f.fields_for @child_daily do |q| %>
    <%= q.label :id %><br />
    <p><%= q.number_field :id %></p>
  <% end %>
 
  <% @questions.each do |q| %>
    <%# debug q %>
    <%= f.fields_for q do |x| %>
      <p><%= x.label q.id %>
      <%= x.check_box :id %></p>
    <% end %>
  
  <% end %>
  
  
<br />
  <%= f.submit %>
<% end %>




<%
=begin
%>

<div class="field">
    <%= f.check_box :question_id %>
  </div>
<%
=end
%>