config/routes.rb
Icec::Application.routes.draw do
  resources :projects

  resources :tops_qualifiers

  resources :tops_questions

  resources :tops_forms do
    get :tops_form, on: :member
    get :tops_form2, on: :member
    post :tops_form, on: :member
    post :tops_form2, on: :member
  end
  
  resources :email_messages do
    get :preview_email, on: :member
  end

  resources :daily_notes

  resources :child_dailies do
    resources :tops_forms #hmm not working for me
    get :tops_report, on: :member
    post :tops_report, on: :member
  end

  resources :children

  match 'take_attendance' => 'child_dailies#take_attendance'
  match 'roll_call' => 'child_dailies#roll_call'
  match 'indexnames' => 'child_dailies#indexnames'
  match 'generate_emails' => 'email_messages#generate_emails'

  

end

app/models/email_message.rb
class EmailMessage < ActiveRecord::Base
  attr_accessible :child_daily_id, :child_id, :daily_note_id, :date, :sent_time, :to_address

  belongs_to :daily_message
  belongs_to :child
  belongs_to :child_daily # May take this one out.

end

app/controllers/email_messages_controller.rb
class EmailMessagesController < ApplicationController
  # GET /email_messages
  # GET /email_messages.json
  def index
    @email_messages = EmailMessage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @email_messages }
    end
  end

  # GET /email_messages/1
  # GET /email_messages/1.json
  def show
    @email_message = EmailMessage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @email_message }
    end
  end

  # GET /email_messages/new
  # GET /email_messages/new.json
  def new
    @email_message = EmailMessage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @email_message }
    end
  end

  # GET /email_messages/1/edit
  def edit
    @email_message = EmailMessage.find(params[:id])
  end

  # POST /email_messages
  # POST /email_messages.json
  def create
    @email_message = EmailMessage.new(params[:email_message])

    respond_to do |format|
      if @email_message.save
        format.html { redirect_to @email_message, notice: 'Email message was successfully created.' }
        format.json { render json: @email_message, status: :created, location: @email_message }
      else
        format.html { render action: "new" }
        format.json { render json: @email_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /email_messages/1
  # PUT /email_messages/1.json
  def update
    @email_message = EmailMessage.find(params[:id])

    respond_to do |format|
      if @email_message.update_attributes(params[:email_message])
        format.html { redirect_to @email_message, notice: 'Email message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @email_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /email_messages/1
  # DELETE /email_messages/1.json
  def destroy
    @email_message = EmailMessage.find(params[:id])
    @email_message.destroy

    respond_to do |format|
      format.html { redirect_to email_messages_url }
      format.json { head :no_content }
    end
  end

  # GET /preview_email/1
  # GET /preview_email/1.json
  def preview_email
    @email_message = EmailMessage.find(params[:id])
    @child = Child.find(@email_message.child_id)
    @child_daily = ChildDaily.find(@email_message.child_daily_id)
    @daily_note = DailyNote.find(@email_message.daily_note_id)
    

    respond_to do |format|
      format.html # preview_email.html.erb
      format.json { render json: @email_message }
    end
  end


  # Generate emails
  def generate_emails
    email_parts = Hash.new()
    email_parts["child_id"] = 2
    UserMailer.child_daily_email(email_parts).deliver
    emails = Hash.new()
    i = 0
    @child_daily = ChildDaily.where("date>?", Date.yesterday)
    @daily_notes = DailyNote.where("date>?", Date.yesterday)
    @child_daily.each do |daily|
      emails[i]["child_id"] = {"child_id" => daily.child_id}
      emails[i]["child_daily_id"] = {"child_daily_id" => daily.id}
      @daily_notes.each do |daily_note|
        emails[i]["daily_note_id"] = {"daily_note_id" => daily_note.id}
      end
      i = i + 1
    end

    emails.each do |i, values|
      c = EmailMessage.create(values)
    end
  end

end

app/helpers/email_messages_helper.rb
module EmailMessagesHelper
end

app/views/email_messages/_form.html.erb
<%= form_for(@email_message) do |f| %>
  <% if @email_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@email_message.errors.count, "error") %> prohibited this email_message from being saved:</h2>

      <ul>
      <% @email_message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :child_id %><br />
    <%= f.number_field :child_id %>
  </div>
  <div class="field">
    <%= f.label :daily_note_id %><br />
    <%= f.number_field :daily_note_id %>
  </div>
  <div class="field">
    <%= f.label :child_daily_id %><br />
    <%= f.number_field :child_daily_id %>
  </div>
  <div class="field">
    <%= f.label :to_address %><br />
    <%= f.text_field :to_address %>
  </div>
  <div class="field">
    <%= f.label :sent_time %><br />
    <%= f.datetime_select :sent_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/email_messages/edit.html.erb
<h1>Editing email_message</h1>

<%= render 'form' %>

<%= link_to 'Show', @email_message %> |
<%= link_to 'Back', email_messages_path %>

app/views/email_messages/generate_emails.html.erb
<h1>Generate Emails Page</h1>



<% @child_daily.each do |child_daily| %>
  <%= child_daily.id %>
<% end %>

<% @daily_notes.each do |daily_note| %>
  <%= daily_note.id %>
<% end %>

app/views/email_messages/index.html.erb
<h1>Listing email_messages</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Date</th>
    <th>Child ID</th>
    <th>Child</th>
    <th>Daily note</th>
    <th>Child daily</th>
    <th>To address</th>
    <th>Sent time</th>
    <th></th>
    <th></th>
    <th></th>
    <th>Email</th>
  </tr>

<% @email_messages.each do |email_message| %>
  <tr>
    <td><%= email_message.id %></td>
    <td><%= email_message.date %></td>
    <td><%= email_message.child_id %></td>
    <% if(email_message.child_id != nil) %>
      <% @child = Child.find(email_message.child_id) %>
      <td><%= @child.first_name %></td>
    <% else %>
      <td></td>
    <% end %>
    <td><%= email_message.daily_note_id %></td>
    <td><%= email_message.child_daily_id %></td>
    <td><%= email_message.to_address %></td>
    <td><%= email_message.sent_time %></td>
    <td><%= link_to 'Show', email_message %></td>
    <td><%= link_to 'Edit', edit_email_message_path(email_message) %></td>
    <td><%= link_to 'Destroy', email_message, confirm: 'Are you sure?', method: :delete %></td>
    <td><%= link_to 'View Email', preview_email_email_message_path(email_message) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Email message', new_email_message_path %>
<%= link_to 'Generate Email messages', generate_emails_path %>

app/views/email_messages/new.html.erb
<h1>New email_message</h1>

<%= render 'form' %>

<%= link_to 'Back', email_messages_path %>

app/views/email_messages/preview_email.html.erb
<h1>Preview Email</h1>
<%
=begin
%>
<%= debug params %>
<%= debug @email_message %>
<%= debug @child %>
<%= debug @child_daily %>
<%= debug @daily_note %>
<%
=end
%>

<p>
<%= "This email is for: " + @child.first_name.capitalize %>
<br />
<%= "This email is addressed to: " + @email_message.to_address %>
</p>

<p>
<% if(@child.mom_first == '')%>
  <% if(@child.dad_first == '')%>
    <%= "Hello!" %>
  <% else %>
    <%= "Hello " + @child.dad_first.capitalize + "!" %>
  <% end %>

<% else %>
  <% if(@child.dad_first == '')%>
    <%= "Hello " + @child.mom_first.capitalize + "!" %>
  <% else %>
    <%= "Hello " + @child.mom_first.capitalize + " and " + @child.dad_first.capitalize + "!" %>
  <% end %>  
<% end %>
</p>

<!--# Daily note for the class. -->
<p><%= @daily_note.note %></p>

<p><%= simple_format("Individual note for " + @child.first_name.capitalize + ": \n" + @child_daily.individual_message) %></p>



<%
=begin
%>
<%= @email_message.sent_time %>
<% if(@email_message.sent_time == ActiveSupport::TimeZone['UTC'].parse("9999-12-31")) %>
  <%= "This email has not been sent yet."%>
<% else %>
  <%= "This email was sent at " + @email_message.sent_time %>
<% end %>

<%
=end
%>
<%= link_to 'New Child daily', new_child_daily_path %>

app/views/email_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @email_message.date %>
</p>

<p>
  <b>Child:</b>
  <%= @email_message.child_id %>
</p>

<p>
  <b>Daily note:</b>
  <%= @email_message.daily_note_id %>
</p>

<p>
  <b>Child daily:</b>
  <%= @email_message.child_daily_id %>
</p>

<p>
  <b>To address:</b>
  <%= @email_message.to_address %>
</p>

<p>
  <b>Sent time:</b>
  <%= @email_message.sent_time %>
</p>


<%= link_to 'Edit', edit_email_message_path(@email_message) %> |
<%= link_to 'Back', email_messages_path %>