config/routes.rb
Icec::Application.routes.draw do
  resources :projects

  resources :tops_qualifiers

  resources :tops_questions

  resources :tops_forms do
    get :tops_form, on: :member
    get :tops_form2, on: :member
    post :tops_form, on: :member
    post :tops_form2, on: :member
  end
  
  resources :email_messages do
    get :preview_email, on: :member
  end

  resources :daily_notes

  resources :child_dailies do
    resources :tops_forms #hmm not working for me
    get :tops_report, on: :member
    post :tops_report, on: :member
  end

  resources :children

  match 'take_attendance' => 'child_dailies#take_attendance'
  match 'roll_call' => 'child_dailies#roll_call'
  match 'indexnames' => 'child_dailies#indexnames'
  match 'generate_emails' => 'email_messages#generate_emails'

  

end

app/models/tops_qualifier.rb
class TopsQualifier < ActiveRecord::Base
  attr_accessible :type_id, :value_id, :value_name, :tops_questions
  
  has_many :tops_questions
end

app/controllers/tops_qualifiers_controller.rb
class TopsQualifiersController < ApplicationController
  # GET /tops_qualifiers
  # GET /tops_qualifiers.json
  def index
    @tops_qualifiers = TopsQualifier.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tops_qualifiers }
    end
  end

  # GET /tops_qualifiers/1
  # GET /tops_qualifiers/1.json
  def show
    @tops_qualifier = TopsQualifier.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tops_qualifier }
    end
  end

  # GET /tops_qualifiers/new
  # GET /tops_qualifiers/new.json
  def new
    @tops_qualifier = TopsQualifier.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tops_qualifier }
    end
  end

  # GET /tops_qualifiers/1/edit
  def edit
    @tops_qualifier = TopsQualifier.find(params[:id])
  end

  # POST /tops_qualifiers
  # POST /tops_qualifiers.json
  def create
    @tops_qualifier = TopsQualifier.new(params[:tops_qualifier])

    respond_to do |format|
      if @tops_qualifier.save
        format.html { redirect_to @tops_qualifier, notice: 'Tops qualifier was successfully created.' }
        format.json { render json: @tops_qualifier, status: :created, location: @tops_qualifier }
      else
        format.html { render action: "new" }
        format.json { render json: @tops_qualifier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tops_qualifiers/1
  # PUT /tops_qualifiers/1.json
  def update
    @tops_qualifier = TopsQualifier.find(params[:id])

    respond_to do |format|
      if @tops_qualifier.update_attributes(params[:tops_qualifier])
        format.html { redirect_to @tops_qualifier, notice: 'Tops qualifier was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tops_qualifier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tops_qualifiers/1
  # DELETE /tops_qualifiers/1.json
  def destroy
    @tops_qualifier = TopsQualifier.find(params[:id])
    @tops_qualifier.destroy

    respond_to do |format|
      format.html { redirect_to tops_qualifiers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tops_qualifiers_helper.rb
module TopsQualifiersHelper
end

app/views/tops_qualifiers/_form.html.erb
<%= form_for(@tops_qualifier) do |f| %>
  <% if @tops_qualifier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tops_qualifier.errors.count, "error") %> prohibited this tops_qualifier from being saved:</h2>

      <ul>
      <% @tops_qualifier.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type_id %><br />
    <%= f.number_field :type_id %>
  </div>
  <div class="field">
    <%= f.label :value_id %><br />
    <%= f.number_field :value_id %>
  </div>
  <div class="field">
    <%= f.label :value_name %><br />
    <%= f.text_field :value_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tops_qualifiers/edit.html.erb
<h1>Editing tops_qualifier</h1>

<%= render 'form' %>

<%= link_to 'Show', @tops_qualifier %> |
<%= link_to 'Back', tops_qualifiers_path %>

app/views/tops_qualifiers/index.html.erb
<h1>Listing tops_qualifiers</h1>

<table>
  <tr>
    <th>Type</th>
    <th>Value</th>
    <th>Value name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tops_qualifiers.each do |tops_qualifier| %>
  <tr>
    <td><%= tops_qualifier.type_id %></td>
    <td><%= tops_qualifier.value_id %></td>
    <td><%= tops_qualifier.value_name %></td>
    <td><%= link_to 'Show', tops_qualifier %></td>
    <td><%= link_to 'Edit', edit_tops_qualifier_path(tops_qualifier) %></td>
    <td><%= link_to 'Destroy', tops_qualifier, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tops qualifier', new_tops_qualifier_path %>

app/views/tops_qualifiers/new.html.erb
<h1>New tops_qualifier</h1>

<%= render 'form' %>

<%= link_to 'Back', tops_qualifiers_path %>

app/views/tops_qualifiers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type:</b>
  <%= @tops_qualifier.type_id %>
</p>

<p>
  <b>Value:</b>
  <%= @tops_qualifier.value_id %>
</p>

<p>
  <b>Value name:</b>
  <%= @tops_qualifier.value_name %>
</p>


<%= link_to 'Edit', edit_tops_qualifier_path(@tops_qualifier) %> |
<%= link_to 'Back', tops_qualifiers_path %>