config/routes.rb
Icec::Application.routes.draw do
  resources :projects

  resources :tops_qualifiers

  resources :tops_questions

  resources :tops_forms do
    get :tops_form, on: :member
    get :tops_form2, on: :member
    post :tops_form, on: :member
    post :tops_form2, on: :member
  end
  
  resources :email_messages do
    get :preview_email, on: :member
  end

  resources :daily_notes

  resources :child_dailies do
    resources :tops_forms #hmm not working for me
    get :tops_report, on: :member
    post :tops_report, on: :member
  end

  resources :children

  match 'take_attendance' => 'child_dailies#take_attendance'
  match 'roll_call' => 'child_dailies#roll_call'
  match 'indexnames' => 'child_dailies#indexnames'
  match 'generate_emails' => 'email_messages#generate_emails'

  

end

app/models/child_daily.rb
class ChildDaily < ActiveRecord::Base
  attr_accessible :child_id, :date, :individual_message, :tops_form, :tops_forms, :tops_questions, :tops_form_attributes
  
  belongs_to :child
  belongs_to :email_message # May take this out.
  
  has_one :tops_form
  #has_many :tops_questions, :through => :tops_forms, :foreign_key => :tops_question_id
  has_many :tops_questions, :through => :tops_form, :foreign_key => :tops_question_id
  
  accepts_nested_attributes_for :tops_form
  accepts_nested_attributes_for :tops_questions
  
  def questions(tops_questions)
    tops_forms.create(:tops_question_id => tops_questions.id)
  end
  
  
end

app/controllers/child_dailies_controller.rb
class ChildDailiesController < ApplicationController
  # GET /child_dailies
  # GET /child_dailies.json
  def index
    @child_dailies = ChildDaily.all
    @children = Child

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @child_dailies }
    end
  end

  def indexnames
    @child_dailies = ChildDaily.all
    @children = Child

    respond_to do |format|
      format.html # index_names.html.erb
      format.json { render json: @child_dailies }
    end
  end

  # GET /child_dailies/1
  # GET /child_dailies/1.json
  def show
    @child_daily = ChildDaily.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @child_daily }
    end
  end

  # GET /child_dailies/new
  # GET /child_dailies/new.json
  def new
    @child_daily = ChildDaily.new(:tops_form => TopsForm.new)
    #@child_daily.tops_form.build.build_tops_question
    @child_daily.tops_form.tops_question

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @child_daily }
    end
  end

  # GET /child_dailies/1/edit
  def edit
    @child_daily = ChildDaily.find(params[:id])
  end

  # POST /child_dailies
  # POST /child_dailies.json
  def create
    @child_daily = ChildDaily.new(params[:child_daily])

    #if(@child_daily.id != nil)
  
      respond_to do |format|
        if @child_daily.save
          format.html { redirect_to @child_daily, notice: 'Child daily was successfully created.' }
          format.json { render json: @child_daily, status: :created, location: @child_daily }
        else
          format.html { render action: "new" }
          format.json { render json: @child_daily.errors, status: :unprocessable_entity }
        end
      end
    #end
  end

  # PUT /child_dailies/1
  # PUT /child_dailies/1.json
  def update
    @child_daily = ChildDaily.find(params[:id])
    #@child_daily.attributes = params[:tops_form]
    #@child_daily.tops_form.update_attributes(params[:id])
    respond_to do |format|
      if @child_daily.update_attributes(params[:child_daily])
        format.html { redirect_to @child_daily, notice: 'Child daily was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @child_daily.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /child_dailies/1
  # DELETE /child_dailies/1.json
  def destroy
    @child_daily = ChildDaily.find(params[:id])
    @child_daily.destroy

    respond_to do |format|
      format.html { redirect_to child_dailies_url }
      format.json { head :no_content }
    end
  end

  # This is for taking daily attendance
  def take_attendance
    @children = Child.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @children }
    end
  end

  def roll_call
    params[:attendance].each do |i, values|
      c = ChildDaily.create(values)
    end
  end
  
  def tops_report
    @child_daily = ChildDaily.find(params[:id])
    @tops_forms = TopsForm.find(:all, @child_daily.child_id)
    #@questions = TopsQuestion.find(@tops_form.tops_question_id)
    #@child_dailies = ChildDailies.all
    #@child_daily = ChildDaily.find(@tops_form.child_daily_id)
    #@child = Child.find(@child_daily.child_id)
    #@questions = TopsQuestion.all
    #@qualifiers = TopsQualifier.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @children }
    end
  end

  def tops_form
    # [@topsform1, @tops_form2]
  end

  def tops_form_attributes=(attributes)
    # Process the attributes hash
  end

end

app/helpers/child_dailies_helper.rb
module ChildDailiesHelper
end

app/views/child_dailies/_form.html.erb
<%= form_for(@child_daily) do |f| %>
  <% if @child_daily.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@child_daily.errors.count, "error") %> prohibited this child_daily from being saved:</h2>

      <ul>
      <% @child_daily.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :child_id %><br />
    <%= f.number_field :child_id %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :individual_message %><br />
    <%= f.text_area :individual_message %>
  </div>
  
  
  
  <%= f.fields_for :tops_form do |t| %>
    <div class="field">
      <%= t.check_box :checked %>
    </div>
  <% end %>
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/child_dailies/edit.html.erb
<h1>Editing child_daily</h1>

<%= render 'form' %>

<%= link_to 'Show', @child_daily %> |
<%= link_to 'Back', child_dailies_path %>

app/views/child_dailies/index.html.erb
<h1>Listing child_dailies</h1>

<table>
  <tr>
    <th>Child ID</th>
    <th>Date</th>
    <th>Individual message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @child_dailies.each do |child_daily| %>
  <tr>
    <td><%= child_daily.child_id %></td>
    <td><%= child_daily.date %></td>
    <td><%= child_daily.individual_message %></td>
    <td><%= link_to 'Show', child_daily %></td>
    <td><%= link_to 'Edit', edit_child_daily_path(child_daily) %></td>
    <td><%= link_to 'Destroy', child_daily, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>


<br />

<%= link_to 'New Child daily', new_child_daily_path %>

app/views/child_dailies/indexnames.html.erb
<h1>Listing child_dailies</h1>

<table>
  <tr>
  	<th>ID</th>
    <th>Child ID</th>
    <th>Child Name</th>
    <th>Date</th>
    <th>Individual message</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    
  </tr>

<% @child_dailies.each do |child_daily| %>
  <tr>
    <td><%= child_daily.id %></td>
    <td><%= child_daily.child_id %></td>
    <% if(child_daily.child_id != nil) %>
      <% @child = @children.find(child_daily.child_id) %>
      <td><%= @child.first_name %></td>
    <% else %>
      <td></td>
    <% end %>
    <td><%= child_daily.date %></td>
    <td><%= child_daily.individual_message %></td>
    <td><%= link_to 'Show', child_daily %></td>
    <td><%= link_to 'Edit', edit_child_daily_path(child_daily) %></td>
    <td><%= link_to 'Destroy', child_daily, confirm: 'Are you sure?', method: :delete %></td>
    <!-- <td><%# link_to 'TOPS Form', tops_form_tops_form_path(tops_form) %></td> -->
    <td><%= link_to 'TOPS Form', child_daily_tops_forms_path(child_daily) %></td>
    <td><%= link_to 'TOPS Report', tops_report_child_daily_path(child_daily) %></td>
    <td><%# link_to 'Show TOPS Form', child_daily_tops_form_path(child_daily) %></td>
  </tr>
<% end %>
</table>


<br />

<%= link_to 'New Child daily', new_child_daily_path %>

app/views/child_dailies/new.html.erb
<h1>New child_daily</h1>

<%= render 'form' %>

<%= link_to 'Back', child_dailies_path %>

app/views/child_dailies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Child:</b>
  <%= @child_daily.child_id %>
</p>

<p>
  <b>Date:</b>
  <%= @child_daily.date %>
</p>

<p>
  <b>Individual message:</b>
  <%= @child_daily.individual_message %>
</p>

<%= link_to 'Edit', edit_child_daily_path(@child_daily) %> |
<%= link_to 'Back', child_dailies_path %>

app/views/child_dailies/take_attendance.html.erb
<h1>Take Attendance</h1>
<p>Today is <%= Date.today %><p>
<p>Please select the children who are here today.<p>
<% kids = Hash.new() %>
<%= form_tag("roll_call", :method => "post") do %>

  <% @children.each do |child| %>

    <%= check_box_tag "attendance[#{child.id}][child_id]", child.id %>
    <%= label_tag(:attendance, child.first_name + " " + child.last_name) %>
    <%= hidden_field_tag "attendance[#{child.id}][date]", Date.today %>
    <br />
  <% end %>


<br />
  <%= submit_tag("Roll Call") %>
<% end %>

app/views/child_dailies/tops_report.html.erb
<h1>TOPS Report</h1>
<p>Today is <%= Date.today %><p>
	
<p> Today, <%= @child_daily.child.first_name.capitalize %>: </p> 

<br />

<%= form_for(@child_daily) do |f| %>

	<table>
	  <tr>
	    <th>Question ID</th>
	    <th></th>
	    <th>Question Description</th>
	    <th>Qualifier Type ID</th>
	    <th>Note</th>
	  </tr>
	<% @child_daily.tops_questions.each do |tq| %>
	  <tr>
	  	<td>
	      <%= tq.id %>
	    </td>
	    <td>
	      <%= f.fields_for :tops_form do |tf_fields| %>
	        <%= tf_fields.check_box :checked %>
	      <% end %>
	    </td>
	    <td>
	      <%= tq.description %>
	    </td>
	    <td>
	      <%= f.fields_for :tops_form do |tf_fields| %>
	        <%= tq.qualifier_type_id %>
	        <%# debug tq.tops_qualifier %>
	        <%= tf_fields.radio_button :qualifier_value_id, "with" %> with assistance 
	        <%= tf_fields.radio_button :qualifier_value_id, "without" %> without assistance
	      <% end %>
	      <%# tq.qualifier_type_id %>
	    </td>
	    <td>
	      <%= f.fields_for :tops_form do |builder| %>
	        <%= builder.text_field :note %>
	      <% end %>
	    </td>
	    
	    
	    
	  
	  
	  </tr>
	<% end %>
	</table>

	<br />
	<%= f.submit %>


<% end %>

<%= debug @tops_forms %>
<%
=begin
%>
<%= form_for(@tops_form) do |f| %>
  
  <%= f.fields_for @child do |c| %>
    <%= c.label :id %><br />
    <p><%= c.check_box :id %></p>
  <% end %>
  
  <%= f.fields_for @child_daily do |q| %>
    <%= q.label :id %><br />
    <p><%= q.number_field :id %></p>
  <% end %>
  
  <% @questions.each do |q| %>
    <%# debug q %>
    <%= f.fields_for q do |x| %>
      <p><%= x.label q.id %>
      <%= x.check_box :id %></p>
    <% end %>
  
  <% end %>
  
  
<br />
  <%= f.submit %>
<% end %>






<div class="field">
    <%= f.check_box :question_id %>
  </div>
<%
=end
%>